version: '3.8'

networks:
  test-app_default:
    driver: overlay

services:
  traefik-main:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=test-app_default"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.le.acme.email=edwardlanekemp@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.tlsChallenge=true"
      - "--api.insecure=true"  # For testing purposes; secure in production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    networks:
      - test-app_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend-main:
    image: edwardkemp/frontend:latest
    labels:
      - "traefik.enable=true"
      # Router for Non-WWW Domain
      - "traefik.http.routers.frontend-main.rule=Host(`edward-codes.com`)"
      - "traefik.http.routers.frontend-main.entrypoints=websecure"
      - "traefik.http.routers.frontend-main.tls.certresolver=le"
      - "traefik.http.services.frontend-main.loadbalancer.server.port=80"
      # Router for WWW Domain with Redirect Middleware
      - "traefik.http.routers.frontend-www-main.rule=Host(`www.edward-codes.com`)"
      - "traefik.http.routers.frontend-www-main.entrypoints=websecure"
      - "traefik.http.routers.frontend-www-main.tls.certresolver=le"
      - "traefik.http.routers.frontend-www-main.middlewares=redirect-www-main"
      # Middleware to Redirect WWW to Non-WWW
      - "traefik.http.middlewares.redirect-www-main.redirectregex.regex=^https?://www\\.(.*)"
      - "traefik.http.middlewares.redirect-www-main.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.redirect-www-main.redirectregex.permanent=true"
    networks:
      - test-app_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
