version: '3.8'

networks:
  test-app_default:
    driver: overlay

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"  # Increased log level for troubleshooting
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=edwardlanekemp@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "letsencrypt:/letsencrypt"
    
    networks:
      - test-app_default
    
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      replicas: 1  # Ensuring only one Traefik instance runs
      update_config:
        parallelism: 1
        delay: 10s

    labels:
      # Dedicated ACME Challenge Router
      - "traefik.http.routers.traefik-acme.rule=PathPrefix(`/.well-known/acme-challenge/`)"
      - "traefik.http.routers.traefik-acme.entrypoints=web"
      - "traefik.http.routers.traefik-acme.priority=1000"
      - "traefik.http.routers.traefik-acme.service=acme-challenge"
      - "traefik.http.services.acme-challenge.loadbalancer.server.port=0"

  frontend:
    image: edwardkemp/frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`edward-codes.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      # Redirect HTTP to HTTPS except for ACME challenges
      - "traefik.http.routers.frontend-http.rule=Host(`edward-codes.com`) && !PathPrefix(`/.well-known/acme-challenge`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    
    networks:
      - test-app_default
    
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  backend:
    image: edwardkemp/backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`edward-codes.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    
    networks:
      - test-app_default
    
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  letsencrypt:
    driver: local
