version: '3.8'

networks:
  test-app_default:
    driver: overlay
    attachable: true  # Allows external services to connect
    labels:
      - "com.example.description=Main traefik network for all services"

secrets:
  cf_api_key:
    external: true

services:
  traefik-main:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=test-app_default"
      - "--providers.docker.swarmmode=true"  # Explicitly enable swarm mode
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.le.acme.dnschallenge=true"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.le.acme.email=edwardlanekemp@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53" 
      - "--api.insecure=false"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      - CF_DNS_API_TOKEN=/run/secrets/cf_api_key
    secrets:
      - cf_api_key
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    networks:
      - test-app_default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager  # Ensure Traefik runs on a manager node
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=test-app_default"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/api/rawdata"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  frontend-main:
    image: edwardkemp/frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-main.rule=Host(`edward-codes.com`)"
      - "traefik.http.routers.frontend-main.entrypoints=websecure"
      - "traefik.http.routers.frontend-main.tls.certresolver=le"
      - "traefik.http.services.frontend-main.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend-www-main.rule=Host(`www.edward-codes.com`)"
      - "traefik.http.routers.frontend-www-main.entrypoints=websecure"
      - "traefik.http.routers.frontend-www-main.tls.certresolver=le"
    networks:
      - test-app_default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
