version: '3.8'

networks:
  test-app_default:
    driver: overlay

services:
  frontend:
    image: edwardkemp/frontend:latest
    ports:
      - "80:80"  # Map container port 80 to host port 80
    networks:
      - test-app_default
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  backend:
    image: edwardkemp/backend:latest
    networks:
      - test-app_default
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
